notebook/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('readnovel.urls', namespace='readnovel')),
]

readnovel/urls.py
"""readnovel URL Configuration
"""
from django.conf.urls import url
from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),

    # novel list
    url(r'^novelList/$', views.novelList, name='novelList'),

    # chapter list
    url(r'^chapterList/(?P<novel_id>\d+)/$', views.chapterList, name='chapterList'),

    # chapter Detail
    url(r'^chapterDetails/(?P<novel_id>\d+)/(?P<serial_number>\d+)/(?P<flag>[-1，0，1]\d*)/$', views.chapterDetails, name='chapterDetails'),

    # new novels
    url(r'^add_novel/$', views.add_novel, name='add_novel'),

    # update novel
    url(r'^update_novel/(?P<novel_id>\d+)/$', views.update_novel, name='update_novel'),

    # update chapter
    url(r'^update_chapter/(?P<novel_id>\d+)/$', views.update_chapter, name='update_chapter'),
]

readnovel/models.py
from django.db import models


# Create your models here.

class BaseInfo(models.Model):
    name = models.CharField(max_length=200, verbose_name=u'名称')
    createtime = models.DateTimeField(auto_now_add=True, verbose_name=u'数据创建时间')
    modifytime = models.DateTimeField(auto_now=True, verbose_name=u'数据最后修改时间')
    remark = models.TextField(verbose_name=u'备注')

    class Meta:
        abstract = True  # 声明为抽象基类

    def __str__(self):
        """ 返回模型的字符串表示 """
        return self.name


class NovelInfo(BaseInfo):
    """ 小说简要信息 """
    avatar = models.CharField(max_length=200, verbose_name=u'小说图片链接')
    author = models.CharField(max_length=20, verbose_name=u'小说作者')
    category = models.CharField(max_length=20, verbose_name=u'小说分类')
    state = models.CharField(max_length=10, verbose_name=u'更新状态')
    words = models.IntegerField(verbose_name=u'字数')
    latest_updatetime = models.CharField(max_length=20, verbose_name=u'最后更新时间')
    latest_chapter = models.CharField(max_length=200, verbose_name=u'最新章节名')
    website = models.CharField(max_length=200, verbose_name=u'小说网站')
    novelId = models.CharField(max_length=200, verbose_name=u'小说ID')
    intro = models.TextField(verbose_name=u'小说简介')
    # user = models.ForeignKey(User, verbose_name=u'所属用户')

    class Meta:
        verbose_name = 'Novel'
        verbose_name_plural = 'Novels'


class Chapter(BaseInfo):
    """ 小说章节信息 """
    href = models.CharField(max_length=200, verbose_name=u'小说具体链接')
    content = models.TextField(verbose_name=u'章节具体内容')
    serial_number = models.IntegerField(verbose_name=u'章节序号')
    novelInfo = models.ForeignKey(NovelInfo, verbose_name=u'所属小说')

    class Meta:
        verbose_name = 'Chapter'
        verbose_name_plural = 'Chapters'

readnovel/views.py
import re
from urllib.request import urlopen

from bs4 import BeautifulSoup
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from readnovel.models import NovelInfo, Chapter


def index(request):
    """主页"""
    return render(request, 'readnovel/index.html')


def novelList(request):
    """view all novels"""
    novelList = NovelInfo.objects.order_by('-modifytime')
    context = {'novelList': novelList}
    return render(request, 'readnovel/novellist.html', context)


def chapterList(request, novel_id):
    """ Chapter List"""
    novelInfo = NovelInfo.objects.get(id=novel_id)
    chapterList = novelInfo.chapter_set.order_by('-serial_number')
    context = {'novelInfo': novelInfo, "chapterList": chapterList}
    return render(request, 'readnovel/chapterlist.html', context)


def chapterDetails(request, novel_id, serial_number, flag):
    """Chapter Details"""
    chapter_serial_number = int(serial_number) + int(flag)

    chapter = Chapter.objects.get(serial_number=chapter_serial_number, novelInfo_id=novel_id)

    if chapter.content is "":
        html = urlopen(chapter.novelInfo.website + chapter.href)
        bsObj = BeautifulSoup(html, "lxml")
        showtxt = bsObj.find("div", {"class": "showtxt"})

        chapter.content = showtxt.get_text('\n\n', 'br/')
        chapter.save()

    try:
        next_chapter_serial_number = int(chapter_serial_number) + int(1)
        next_chapter = Chapter.objects.get(serial_number=next_chapter_serial_number, novelInfo_id=novel_id)
        context = {'chapter': chapter, 'novelInfo': chapter.novelInfo, 'next_flag': 'true'}
    except:
        context = {'chapter': chapter, 'novelInfo': chapter.novelInfo, 'next_flag': 'false'}

    return render(request, 'readnovel/chapterdetails.html', context)


def add_novel(request):
    """add novel"""
    if request.POST:
        novelInfo = NovelInfo()
        novelInfo.website = request.POST['website']
        novelInfo.novelId = request.POST['novelId']
        saveNovelInfo(novelInfo)
        novelInfo.save()

    return HttpResponseRedirect(reverse('readnovel:novelList'))


def update_novel(request, novel_id):
    novelInfo = NovelInfo.objects.get(id=novel_id)
    saveNovelInfo(novelInfo)
    novelInfo.save()
    messages.success(request, '更新成功！')

    return HttpResponseRedirect(reverse('readnovel:novelList'))


def saveNovelInfo(novelInfo):
    html = urlopen(novelInfo.website + novelInfo.novelId)
    bsObj = BeautifulSoup(html, "lxml")
    novelInfo.name = bsObj.h2.get_text()
    cover = bsObj.find("div", {"class": "cover"})
    novelInfo.avatar = cover.find("img").attrs['src']
    small = bsObj.find("div", {"class": "small"})
    for child in small.children:
        label = child.get_text().split("：")[0]
        value = child.get_text().split("：")[1]
        if label == "作者":
            novelInfo.author = value
        elif label == "分类":
            novelInfo.category = value
        elif label == "状态":
            novelInfo.state = value
        elif label == "字数":
            novelInfo.words = value
        elif label == "更新时间":
            novelInfo.latest_updatetime = value
        elif label == "最新章节":
            novelInfo.latest_chapter = value
    intro = bsObj.find("div", {"class": "intro"})
    introArray = intro.get_text().split("：")
    novelInfo.intro = introArray[1].replace("\u3000", "")


def update_chapter(request, novel_id):
    novelInfo = NovelInfo.objects.get(id=novel_id)
    chapters = novelInfo.chapter_set.order_by('-createtime')

    html = urlopen(novelInfo.website + novelInfo.novelId)
    bsObj = BeautifulSoup(html, "lxml")

    chapterList = bsObj.findAll("a", {"href": re.compile(novelInfo.novelId + "\/-?[1-9]\d*\.html")})

    update_count = len(chapterList[13:]) - len(chapters)

    chapterListToDB = chapterList[-update_count:]

    if update_count > 0:
        for index in range(len(chapterListToDB)):
            chapter = Chapter()
            chapter.novelInfo = novelInfo
            chapter.href = chapterListToDB[index]['href']
            chapter.name = chapterListToDB[index].get_text()
            if len(chapters) == 0:
                chapter.serial_number = index
            else:
                chapter.serial_number = len(chapters) + int(index)
            chapter.save()
        messages.success(request, '更新成功！')
    else:
        messages.success(request, '没有新章节！')

    return HttpResponseRedirect(reverse('readnovel:novelList'))

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="/static/img/favicon.png">

    <title>FlatLab - Flat & Responsive Bootstrap Admin Template</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="/static/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="/static/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen"/>
    <link rel="stylesheet" href="/static/css/owl.carousel.css" type="text/css">

      <!--right slidebar-->
      <link href="/static/css/slidebars.css" rel="stylesheet">

    <!-- Custom styles for this template -->

    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/css/mystyle.css" rel="stylesheet">
    <link href="/static/css/style-responsive.css" rel="stylesheet" />

  </head>

  <body>

  <section id="container" >
        <!--header start-->
        <header class="header white-bg">
          <div class="sidebar-toggle-box">
              <div data-original-title="Toggle Navigation" data-placement="right" class="fa fa-bars tooltips"></div>
          </div>
          <!--logo start-->
          <a href="novellist.html" class="logo" >Note<span>Book</span></a>
          <!--logo end-->
          <div class="nav notify-row" id="top_menu">
              <!--  notification start -->
              <ul class="nav top-menu">
                  <!-- settings start -->
                  <li class="dropdown">
                      <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                          <i class="fa fa-tasks"></i>
                          <span class="badge bg-success">1</span>
                      </a>
                      <ul class="dropdown-menu extended tasks-bar">
                          <div class="notify-arrow notify-arrow-green"></div>
                          <li>
                              <p class="green">You have 1 pending tasks</p>
                          </li>
                          <li>
                              <a href="#">
                                  <div class="task-info">
                                      <div class="desc">Dashboard v1.3</div>
                                      <div class="percent">40%</div>
                                  </div>
                                  <div class="progress progress-striped">
                                      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                          <span class="sr-only">40% Complete (success)</span>
                                      </div>
                                  </div>
                              </a>
                          </li>
                      </ul>
                  </li>
                  <!-- settings end -->
                  <!-- inbox dropdown start-->
                  <li id="header_inbox_bar" class="dropdown">
                      <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                          <i class="fa fa-envelope-o"></i>
                          <span class="badge bg-important">5</span>
                      </a>
                      <ul class="dropdown-menu extended inbox">
                          <div class="notify-arrow notify-arrow-red"></div>
                          <li>
                              <p class="red">You have 5 new messages</p>
                          </li>
                          <li>
                              <a href="#">
                                  <span class="photo"><img alt="avatar" src="/static/img/avatar-mini.jpg"></span>
                                  <span class="subject">
                                    <span class="from">Jonathan Smith</span>
                                    <span class="time">Just now</span>
                                    </span>
                                  <span class="message">
                                        Hello, this is an example msg.
                                    </span>
                              </a>
                          </li>
                      </ul>
                  </li>
                  <!-- inbox dropdown end -->
                  <!-- notification dropdown start-->
                  <li id="header_notification_bar" class="dropdown">
                      <a data-toggle="dropdown" class="dropdown-toggle" href="#">

                          <i class="fa fa-bell-o"></i>
                          <span class="badge bg-warning">7</span>
                      </a>
                      <ul class="dropdown-menu extended notification">
                          <div class="notify-arrow notify-arrow-yellow"></div>
                          <li>
                              <p class="yellow">You have 7 new notifications</p>
                          </li>
                          <li>
                              <a href="#">
                                  <span class="label label-danger"><i class="fa fa-bolt"></i></span>
                                  Server #3 overloaded.
                                  <span class="small italic">34 mins</span>
                              </a>
                          </li>
                      </ul>
                  </li>
                  <!-- notification dropdown end -->
              </ul>
          </div>
          <div class="top-nav ">
              <ul class="nav pull-right top-menu">
                  <li>
                      <input type="text" class="form-control search" placeholder="Search">
                  </li>
                  <!-- user login dropdown start-->
                  <li class="dropdown">
                      <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                          <img alt="" src="/static/img/avatar1_small.jpg">
                          <span class="username">Jhon Doue</span>
                          <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu extended logout">
                          <div class="log-arrow-up"></div>
                          <li><a href="#"><i class=" fa fa-suitcase"></i>Profile</a></li>
                          <li><a href="#"><i class="fa fa-cog"></i> Settings</a></li>
                          <li><a href="#"><i class="fa fa-bell-o"></i> Notification</a></li>
                          <li><a href="login.html"><i class="fa fa-key"></i> Log Out</a></li>
                      </ul>
                  </li>
                  <!-- user login dropdown end -->
              </ul>
          </div>
        </header>
        <!--header end-->
        <!--sidebar start-->
        <aside>
          <div id="sidebar"  class="nav-collapse">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
                  <li>
                      <a id="index" href="{% url 'readnovel:index' %}"  class="active" >
                          <i class="fa fa-dashboard"></i>
                          <span>Dashboard</span>
                      </a>
                  </li>
                  <li class="sub-menu">
                      <a id="novel" href="{% url 'readnovel:novelList' %}">
                          <i class="fa fa-glass"></i>
                          <span>Read Novel</span>
                      </a>
                  </li>
                  <li>
                      <a  href="login.html">
                          <i class="fa fa-user"></i>
                          <span>Login Page</span>
                      </a>
                  </li>
              </ul>
              <!-- sidebar menu end-->
          </div>
        </aside>
        <!--sidebar end-->

    <!--main content start-->
    <section id="main-content" style="overflow-y: hidden">
        <section class="wrapper site-min-height-own">

        {% block header %}{% endblock header %}

        {% block content %}{% endblock content %}

        </section>
    </section>
    <!--main content end-->

      <!--footer start-->
      <footer class="site-footer">
          <div class="text-center">
              2013 &copy; FlatLab by VectorLab.
              <a href="#" class="go-top">
                  <i class="fa fa-angle-up"></i>
              </a>
          </div>
      </footer>
      <!--footer end-->
  </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="/static/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="/static/js/jquery.scrollTo.min.js"></script>
    <script src="/static/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="/static/js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="/static/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="/static/js/owl.carousel.js" ></script>
    <script src="/static/js/jquery.customSelect.min.js" ></script>
    <script src="/static/js/respond.min.js" ></script>

    <!--right slidebar-->
    <script src="/static/js/slidebars.min.js"></script>

    <!--common script for all pages-->
    <script src="/static/js/common-scripts.js"></script>

    <!--script for this page-->
    <script src="/static/js/sparkline-chart.js"></script>
    <script src="/static/js/easy-pie-chart.js"></script>
    <script src="/static/js/count.js"></script>

 {% block myscript %}{% endblock myscript %}

  </body>
</html>

templates/readnovel/chapterdetails.html
{% extends "base/base.html" %}

<!-- page start-->

{% block header %}
    <section class="panel">
        <header class="panel-heading">
            {{ chapter.name }}
            <span class="pull-right">
              {% comment %}<button type="button" id="loading-btn" class="btn btn-warning btn-xs"><i class="fa fa-refresh"></i> Refresh</button>{% endcomment %}
              <a href="{% url 'readnovel:chapterList' novelInfo.id %}">
                  <button type="button" id="reply-btn" class="btn btn-primary btn-xs">
                      <i class="fa  fa-reply"></i> reply
                  </button>
              </a>
          </span>
        </header>
    </section>
{% endblock header %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <section class="panel">
                <div class="panel-body">
                    <div class="m-left10">
                        <h5>{{ chapter.content | linebreaks }}</h5>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <!--main content end-->
    <div class="row">
        <div class="col-md-12 col-md-offset-5">
            <a href="{% url 'readnovel:chapterDetails' novelInfo.id chapter.serial_number -1 %}">
                <button type="button" class="btn btn-round btn-primary"><i class="fa fa-hand-o-left"></i> 上一章</button>
            </a>
            {% if next_flag == 'true' %}
                <a class="m-left20" href="{% url 'readnovel:chapterDetails' novelInfo.id chapter.serial_number 1 %}">
                    <button type="button" class="btn btn-round btn-primary"><i class="fa fa-hand-o-right"></i> 下一章</button>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock content %}

<!-- page end-->

{% block myscript %}
    <script type="text/javascript">
        $("#index").removeClass("active");
        $("#novel").addClass("active");
    </script>
{% endblock myscript %}

templates/readnovel/chapterlist.html
{% extends "base/base.html" %}

<!-- page start-->

{% block header %}
    <section class="panel">
        <header class="panel-heading">
            {{ novelInfo.name }}
            <span class="pull-right">
                  {% comment %}<button type="button" id="loading-btn" class="btn btn-warning btn-xs"><i class="fa fa-refresh"></i> Refresh</button>{% endcomment %}
                  <a href="{% url 'readnovel:novelList' %}"><button type="button" id="reply-btn" class="btn btn-primary btn-xs"><i class="fa  fa-reply"></i> reply</button></a>
              </span>
        </header>
    </section>
{% endblock header %}

{% block content %}
    <div class="row">
    {% for chapter in chapterList %}
        <div class="col-lg-3">
            <section class="panel">
                <div class="panel-body ellipsis"><a href="{% url 'readnovel:chapterDetails' novelInfo.id chapter.serial_number 0 %}">{{ chapter.name }}</a></div>
            </section>
        </div>
    {% empty %}
        <div class="col-md-4 col-sm-4">
            <div class="panel">
                <div class="panel-body">
                    <span class="col-md-6 col-sm-6">未更新章节，请点击更新按钮！</span>
                    <a href="{% url 'readnovel:update_chapter' novelInfo.id %}"><button type="button" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i> 更新章节 </button></a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    <!--main content end-->
{% endblock content %}

<!-- page end-->

 {% block myscript %}
     <script type="text/javascript">
         $("#index").removeClass("active");
         $("#novel").addClass("active");
     </script>
 {% endblock myscript %}

templates/readnovel/novellist.html
{% extends "base/base.html" %}

<!-- page start-->

{% block header %}

    <section class="panel">
        <header class="panel-heading">
            小说列表
            <span class="pull-right">
                  {% comment %}<button type="button" id="loading-btn" class="btn btn-info btn-xs"><i class="fa fa-refresh"></i> 刷新</button>{% endcomment %}
                  <a data-toggle="modal" href="#addNovelModal"><button type="button" id="plus-btn" class="btn btn-primary btn-xs m-left10"><i class="fa fa-plus"></i> 新增</button></a>
              </span>
        </header>
    </section>

{% endblock header %}

{% block content %}

    {% if messages %}
        <div class="alert alert-success alert-block fade in">
          <button data-dismiss="alert" class="close close-sm" type="button">
              <i class="fa fa-times"></i>
          </button>
            {% for message in messages %}
                <p><i class="fa fa-ok-sign"></i>{{ message.message }}</p>
            {% endfor %}
        </div>
    {% endif %}

    <div class="directory-info-row-own">
        <div class="row">
            {% for novel in novelList %}
                <div class="col-md-4 col-sm-4">
                <div class="panel">
                    <div class="panel-body">
                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="thumb media-object novel-img" src="{{ novel.website }}{{ novel.avatar }}" alt="">
                            </a>
                            <div class="media-body">
                                <h4><a href="{% url 'readnovel:chapterList' novel.id %}">{{ novel.name }}</a><span class="text-muted small"> - {{ novel.category }}</span></h4>
                                <div class="row p-details">
                                    <div class="bio-row-own">
                                        <span class="bold">作&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;者 </span>: {{ novel.author }}
                                    </div>
                                    <div class="bio-row-own">
                                        <span class="bold">更新时间 </span>: {{ novel.latest_updatetime }}
                                    </div>
                                    <div class="bio-row-own">
                                        <span class="bold">最新章节 </span>:  {{ novel.latest_chapter }}
                                    </div>
                                    <div class="bio-row-own">
                                        <span class="bold">原网站链接 </span>:  <a href="{{ novel.website }}{{ novel.novelId }}"  target="_blank">{{ novel.website }}{{ novel.novelId }}</a>
                                    </div>
                                    <div class="bio-row-own">
                                        <a href="{% url 'readnovel:update_novel' novel.id %}">
                                            <button type="button" class="btn btn-info "><i class="fa fa-refresh"></i>更新基本信息 </button>
                                        </a>
                                        <a href="{% url 'readnovel:update_chapter' novel.id %}">
                                            <button type="button" class="btn btn-info m-left10"><i class="fa fa-refresh"></i>更新章节</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
                <div class="col-md-4 col-sm-4">
                <div class="panel">
                    <div class="panel-body">
                        <span class="col-md-3 col-sm-3">未添加小说</span>
                        <a  data-toggle="modal" href="#addNovelModal"><button type="button" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i> 新增</button></a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <!-- vertical center right side Modal start -->
    <div class="modal fade modal-dialog-center right-modal-with-space" id="addNovelModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content-wrap">
              <div class="modal-content">
                  <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                      <h4 class="modal-title">添加小说</h4>
                  </div>
                  <div class="modal-body">
                      <section class="panel">
                          <header class="panel-heading">添加小说</header>
                          <div class="panel-body">
                              <form class="form-horizontal" role="form" action="{% url 'readnovel:add_novel' %}" method="post">
                                  {% csrf_token %}
                                  <div class="form-group">
                                      <label for="inputEmail1" class="col-md-2 col-sm-2 control-label">网站</label>
                                      <div class="col-md-10">
                                          <input type="text" class="form-control" name="website" required readonly value="http://www.biqukan.com/">
                                      </div>
                                  </div>
                                  <div class="form-group">
                                      <label for="inputPassword1" class="col-md-2 col-sm-2 control-label">小说编号</label>
                                      <div class="col-md-10">
                                          <input type="text" class="form-control" name="novelId" required placeholder="Novel ID">
                                      </div>
                                  </div>
                                  <div class="form-group">
                                      <div class="col-md-offset-10 col-md-10">
                                          <button type="submit" class="btn btn-info">添加</button>
                                      </div>
                                  </div>
                              </form>
                          </div>
                      </section>
                  </div>
              </div>
          </div>
      </div>
    </div>
    <!-- vertical center right side Modal end -->

{% endblock content %}

 {% block myscript %}
     <script type="text/javascript">
         $("#index").removeClass("active");
         $("#novel").addClass("active");

     </script>
 {% endblock myscript %}

<!-- page end-->